### ISSUE TITLE
FR: please support streaming of logs

### ISSUE THREAD

**Issue by linde** [GoogleCloudPlatform/kubectl-ai#122]
was in a situation where I had a workload I wanted to watch when it was starting up (ie tailing its logs). this workload happend to take a long time to become scheduled/runnable, so i was hoping `kubectl ai` could support a prompt along the lines of the following:

```
could you please wait until the workload-with-warmup deployment is running, then tail its logs
```

it is worth noting the following works just as intended:

```
could you please wait until the workload-with-warmup deployment is running, then cat its logs
```

it prints the logs and even remarks that there is just one line at that point:

```
>>> could you please wait until the workload-with-warmup deployment is running, then cat its logs

  Okay, I will wait for the  workload-with-warmup  deployment to become available 
  and then fetch its logs. This might take a moment.                              

  Running: kubectl wait --for=condition=Available deployment/workload-with-warmup --timeout=120s

  The deployment  workload-with-warmup  is now available! ✅                      
                                                                                  
  Now, I'll fetch the logs for you.                                               

  Running: kubectl logs deployment/workload-with-warmup

  Okay, the deployment  workload-with-warmup  is running and here are the latest  
  logs from its default container ( workload ):                                   
                                                                                  
    Mon Apr 28 18:41:50 UTC 2025                                                  
                                                                                  
  It seems there's only one log line since the deployment became available. Let me
  know if you need anything else! 😊                                              

```

when I asked it to tail the logs, it does this which is remarkable, but doesn't handle the streaming part:

```
$ kubectl ai 

  Hey there, what can I help you with today?                                      



>>> could you please wait until the workload-with-warmup deployment is running, then tail its logs           

  Okay, I can do that. I'll wait for the deployment  workload-with-warmup  to     
  become                                                                          
  available and then start streaming its logs.                                    


  Running: kubectl wait --for=condition=available deployment/workload-with-warmup --timeout=300s

  Running: kubectl logs -f deployment/workload-with-warmup

```
it just never returns.

I get this is prob a challenge to handle the streaming, just filing a FR to capture the useful CUJ.

here is the config I had for my "workload":

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-with-warmup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-with-warmup
  template:
    metadata:
      labels:
        app: workload-with-warmup
    spec:
      initContainers:
        - name: warmup
          image: ubuntu:latest
          args: ['bash', '-c', 'for i in `seq 1 30`; do echo warming up $i; sleep 1s; done']
      containers:
        - name: workload
          image: ubuntu:latest
          args: ['bash', '-c', 'while true; do sleep 3s && date; done']
```
