### ISSUE TITLE
Bug: custom tools don't seem to work

### ISSUE THREAD

**Issue by Keyruu** [GoogleCloudPlatform/kubectl-ai#250]
Hello, thanks for the awesome tool! I am on version 0.0.9 and have this in my `~/.config/kubectl-ai/tools.yaml`:
```yaml
- name: aws
  description: "Interacts with Amazon Web Services (AWS). Use this tool to manage AWS resources like EC2 instances, S3 buckets, IAM users, EKS clusters, etc."
  command: "aws"
  command_desc: |
    The AWS Command Line Interface (CLI) is a unified tool to manage your AWS services.
    Syntax: aws [service] [command] [parameters] [options]

    Common Services and Commands:
    - ec2: Manages Amazon Elastic Compute Cloud (EC2) instances.
      - describe-instances: Describes one or more of your instances.
        Example: aws ec2 describe-instances --instance-ids i-1234567890abcdef0
      - run-instances: Launches the specified number of instances using an AMI for which you have permissions.
        Example: aws ec2 run-instances --image-id ami-0abcdef1234567890 --count 1 --instance-type t2.micro
      - start-instances: Starts an Amazon EBS-backed instance that you've previously stopped.
        Example: aws ec2 start-instances --instance-ids i-0987654321fedcba0
      - stop-instances: Stops an Amazon EBS-backed instance.
        Example: aws ec2 stop-instances --instance-ids i-0987654321fedcba0
    - s3: Manages Amazon Simple Storage Service (S3) buckets and objects.
      - ls [S3Uri] [flags]: Lists S3 objects and common prefixes under a prefix or all S3 buckets.
        Example: aws s3 ls s3://my-bucket/my-folder/
      - cp <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri> [flags]: Copies a local file or S3 object to another location locally or in S3.
        Example: aws s3 cp my-file.txt s3://my-bucket/
      - sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri> [flags]: Syncs directories and S3 prefixes.
        Example: aws s3 sync ./my-local-dir s3://my-bucket/my-s3-dir
      - mb <S3Uri> [flags]: Creates an S3 bucket.
        Example: aws s3 mb s3://new-bucket-name --region us-east-1
      - rb <S3Uri> [flags]: Deletes an S3 bucket.
        Example: aws s3 rb s3://bucket-to-delete --force
    - iam: Manages AWS Identity and Access Management (IAM) users, groups, roles, and policies.
      - list-users: Lists the IAM users.
        Example: aws iam list-users
      - create-user --user-name <value>: Creates a new IAM user.
        Example: aws iam create-user --user-name new-user
      - list-roles: Lists the IAM roles.
        Example: aws iam list-roles
    - eks: Manages Amazon Elastic Kubernetes Service (EKS) clusters.
      - describe-cluster --name <clusterName> [flags]: Describes an Amazon EKS cluster.
        Example: aws eks describe-cluster --name my-eks-cluster --region us-west-2
      - list-clusters [flags]: Lists the Amazon EKS clusters in your AWS account in the specified Region.
        Example: aws eks list-clusters --region us-east-1
      - update-kubeconfig --name <clusterName> [flags]: Gets or updates an EKS cluster's kubeconfig file.
        Example: aws eks update-kubeconfig --name my-cluster --region eu-central-1
      - create-nodegroup --cluster-name <value> --nodegroup-name <value> --subnets <value> --node-role <value> [flags]: Creates a managed node group for an Amazon EKS cluster.
        Example: aws eks create-nodegroup --cluster-name my-cluster --nodegroup-name my-nodegroup --subnets subnet-xxxxxxxxxxxxxxxxx subnet-yyyyyyyyyyyyyyyyy --node-role arn:aws:iam::123456789012:role/EKSNodeRole --instance-types t3.medium
    - logs: Manages Amazon CloudWatch Logs.
      - describe-log-groups [flags]: Lists the specified log groups.
        Example: aws logs describe-log-groups --log-group-name-prefix /aws/eks/
      - get-log-events --log-group-name <value> --log-stream-name <value> [flags]: Lists log events from the specified log stream.
        Example: aws logs get-log-events --log-group-name /my/log/group --log-stream-name my-log-stream

    Use 'aws [service] [command] help' or 'aws help' for more information.
    Ensure AWS CLI is configured with appropriate credentials and default region.
```

But when I then let the AI fetch something for me, it doesn't work:
```
❯ kubectl ai                                                                                                                                                                                                                                                                                                                                                                                           at 08:18:35

  Hey there, what can I help you with today?


>>> can you tell me what node types are deployed in the cluster
  Running: kubectl get nodes -o json


  The cluster has the following node instance types:

  • r4.xlarge
  • t2.2xlarge
  • t2.xlarge
  • t3.medium
  • r6a.large
  • c5a.xlarge
  • i3.4xlarge
  • i3.2xlarge


>>> how expensive are these nodetypes, try to get that info via aws cli
  Running: pricing get-products --service-code AmazonEC2 --filters Type=TERM_MATCH,Field=instanceType,Value=r4.xlarge Type=TERM_MATCH,Field=location,Value="EU (Frankfurt)" Type=TERM_MATCH,Field=operatingSystem,Value=Linux Type=TERM_MATCH,Field=preInstalledSw,Value=NA Type=TERM_MATCH,Field=tenancy,Value=Shared --region us-east-1 --output json

  Do you want to proceed ?
  1) Yes
  2) Yes, and don't ask me again
  3) No
  Enter your choice (number): y

  Invalid choice. Please enter one of: 1, 2, 3
  Enter your choice (number): 1
  Running: ec2 describe-spot-price-history --instance-types r4.xlarge --product-descriptions "Linux/UNIX" --region eu-central-1 --output json

  Do you want to proceed ?
  1) Yes
  2) Yes, and don't ask me again
  3) No
  Enter your choice (number): 1

  I am unable to retrieve the pricing information for the node types using the
  AWS CLI.

  However, I can provide you with the list of node types, and you can manually
  check their pricing in the AWS console or using the AWS pricing calculator.

  The node types are:

  • r4.xlarge
  • t2.2xlarge
  • t2.xlarge
  • t3.medium
  • r6a.large
  • c5a.xlarge
  • i3.4xlarge
  • i3.2xlarge

  I can also try to get the price for each node type individually if you would like.
```

@janetkuo I think you added the custom tools right? Maybe you could take a look at this.
