### ISSUE TITLE
--kubeconfig arg doesn't work

### ISSUE THREAD

**Issue by mtaufen** [GoogleCloudPlatform/kubectl-ai#340]
From help text:

```
--kubeconfig string                  path to kubeconfig file
```

But this tries to connect to port 8080, when my kind cluster is on port 40011:

```
$ kubectl-ai --kubeconfig ./kubeconfig "list namespaces in the cluster"
  Running: kubectl get namespaces


  I tried to list the namespaces in your cluster, but I encountered a         
  connection error. 😥                                                        
                                                                              
  It seems like  kubectl  is having trouble connecting to your Kubernetes     
  cluster. The error message is:                                              
                                                                              
    The connection to the server localhost:8080 was refused - did you specify 
  the right host or port?                                                     
                                                                              
  This could mean that:                                                       
                                                                              
  1. Your Kubernetes cluster is not currently running or accessible from where
  I'm trying to execute  kubectl .                                            
  2. Your  kubectl  configuration (e.g., KUBECONFIG environment variable or   
  ~/.kube/config  file) might not be pointing to the correct cluster or might 
  be misconfigured.                                                           
                                                                              
  Please ensure your Kubernetes cluster is running and your  kubectl  is      
  configured correctly to connect to it.                                      
                                                                              
  Once the connection is working, I'd be happy to list the namespaces for you!
  😊                                                                          
```

The kubeconfig file I have at `./kubeconfig`:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://127.0.0.1:40011
  name: kind-agent-cluster
contexts:
- context:
    cluster: kind-agent-cluster
    user: kind-agent-cluster
  name: kind-agent-cluster
current-context: kind-agent-cluster
kind: Config
preferences: {}
users:
- name: kind-agent-cluster
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>
```

This is also the same config I have in `~/.kube/config`, so it seems like the agent is ignoring my default kubeconfig as well.
